services:
  postgres:
    image: postgres:18-alpine
    container_name: nomad-postgres
    environment:
      POSTGRES_USER: nomad_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nomad_db
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nomad_user -d nomad_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  k6:
    image: grafana/k6:latest
    container_name: k6-load-test
    volumes:
      - ./:/scripts
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: ["testing"]