FROM openjdk:24-jdk-slim AS builder
WORKDIR /app
COPY . .
RUN chmod +x gradlew
RUN ./gradlew :loom-app:bootJar --no-daemon

FROM openjdk:24-slim
WORKDIR /app
COPY --from=builder /app/loom-app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-Xmx256m", "-Xms256m", "-jar", "app.jar"]
